
#生产环境prod
server:
  port: 8089
  servlet:
    context-path: /mylottery
  tomcat:
    uri-encoding: UTF-8
spring:
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 设置时间返回格式
    time-zone: GMT+8
  datasource:
    # 主数据库
    db1:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: KLxs8888
      jdbc-url: jdbc:mysql://rm-bp178mt2593im687xjo.mysql.rds.aliyuncs.com:3306/lottery?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&rewriteBatchedStatements=TRUE
      type: com.alibaba.druid.pool.DruidDataSource
    # ecc正式
    db2:
      driverClassName: com.mysql.jdbc.Driver
      username: baho_read
      password: Baho@123
      jdbc-url: jdbc:mysql://rr-k2jai63p1k611760v.mysql.zhangbei.rds.aliyuncs.com:3306/baho_ecc_zhengshi?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&rewriteBatchedStatements=TRUE
      type: com.alibaba.druid.pool.DruidDataSource
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: -1    #上传文件大小不限制
      max-request-size: -1 #文件大小不限制
logging:
  file: mylottery.log
  pattern:
    console: 【BAHO】[%d{yyyy-MM-dd HH:mm:ss}] %yellow(%-5level)[%-15thread] %logger{60}\(%line\) %msg%n #日志格式
  level:
    com.lottery.mylottery.dao: DEBUG
